MoreAdvancedCalculator/Models/Birth.cs
public class Birth {
    public String Name { get; set; }
    public double? Age { get; set; }
    public bool IsValid()
    {
        return Name != null && Age != null && Age > 0 && Age < DateTime.Now.Year;
    }

    public int Calculate()
    {
        return (int) (DateTime.Now.Year - Age);
    }
}

MoreAdvancedCalculator/Models/Calculator.cs
using static MoreAdvancedCalculator.Controllers.CalculatorController;

public class Calculator
{
    public Operator? Op { get; set; }
    public double? X { get; set; }
    public double? Y { get; set; }

    public String OpString
    {
        get
        {
            switch (Op)
            {
                case Operator.Add:
                    return "+";
                case Operator.Sub:
                    return "-";
                case Operator.Mul:
                    return "*";
                case Operator.Div:
                    return "/";
                case Operator.Pow:
                    return "^";
                case Operator.Sin:
                    return "Sin";
                default:
                    return "";
            }
        }
    }

    public bool IsValid()
    {
        return Op != null && X != null && Y != null;
    }

    public double Calculate() {
            double? result = double.NaN;

            switch(Op)
            {
                case Operator.Add:
                    result = X + Y;
                    break;
                case Operator.Sub:
                    result = X - Y;
                    break;
                case Operator.Mul:
                    result = X * Y;
                    break;
                case Operator.Div:
                    if(Y == 0)
                    {
                        break;
                    }
                    result = X / Y;
                    break;
                case Operator.Pow:
                    result = Math.Pow(X.Value,Y.Value);
                    break;
                case Operator.Sin:
                    result = Math.Sin(X.Value * Math.PI / 180);
                    result = (double)Math.Round((decimal)result * 1000000) / 1000000;
                    break;                                      
            }

            return (double)result;
    }
}

MoreAdvancedCalculator/Models/ErrorViewModel.cs
namespace MoreAdvancedCalculator.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MoreAdvancedCalculator/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;

namespace MoreAdvancedCalculator.Controllers;

public class BirthController : Controller {

    public IActionResult Form() {
        return View();
    }

    [HttpPost]
    public IActionResult Result(Birth model) {
        if (!model.IsValid())
        {
            return View("Error");
        }
        return View(model);
    }
}

MoreAdvancedCalculator/Controllers/CalculatorController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MoreAdvancedCalculator.Models;

namespace MoreAdvancedCalculator.Controllers;

public class CalculatorController : Controller
{

    public IActionResult Form()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Result([FromForm] Calculator model)
    {
    if (!model.IsValid())
    {
        return View("Error");
    }
    return View(model);
    }

    public enum Operator
    {
        Add,Sub,Mul,Div,Pow,Sin
    }
}

MoreAdvancedCalculator/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MoreAdvancedCalculator.Models;

namespace MoreAdvancedCalculator.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MoreAdvancedCalculator/Views/Birth/Form.cshtml
@{
    ViewBag.Title = "Imie nazwisko";
    Layout = "_layout";
}

<div class="container">
    <div class="row justify-content-md-center">
    <div class="col-6">
            <h2>Imie i nazwisko!</h2>
        <form action="Result" method="POST">
            <div class="mb-3">
                <label class="form-label" for="name">Imie</label>
                <input class="form-control" type="text" name="name" id="name"/>
            </div>
            <div class="mb-3">
                <label class="form-label" for="age">Rok urodzenia</label>
                <input class="form-control" type="number" min="1" name="age" id="age"/>
            </div>
            
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Oblicz</button>
            </div>
        </form>
    </div>
</div>

MoreAdvancedCalculator/Views/Birth/Result.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>Witaj @Model.Name, masz @Model.Calculate() lat!</H3>

MoreAdvancedCalculator/Views/Calculator/Form.cshtml
@{
    ViewBag.Title = "Calculator Form";
    Layout = "_layout";
}

<div class="container">
    <div class="row justify-content-md-center">
    <div class="col-6">
            <h2>Kalkulator</h2>
        <form action="Result" method="POST">
            <div class="mb-3">
                <label class="form-label" for="X">Liczba 1</label>
                <input class="form-control" type="number" name="X" step="0.00001" id="X"/>
            </div>
            <div class="mb-3">
                <select name="op">
                    <option value="add">+</option>
                    <option value="sub">&minus;</option>
                    <option value="mul">&times;</option>
                    <option value="div">&divide;</option>
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label" for="Y">Liczba 2</label>
                <input class="form-control" type="number" name="Y" step="0.00001" id="Y"/>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Oblicz</button>
            </div>
        </form>
    </div>
</div>

MoreAdvancedCalculator/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X  @Model.OpString @Model.Y = @Model.Calculate()</H3>

MoreAdvancedCalculator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MoreAdvancedCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoreAdvancedCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoreAdvancedCalculator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoreAdvancedCalculator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Imie i Nazwisko</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MoreAdvancedCalculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>